# Generated by Django 5.2.12 on 2026-04-17 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True, verbose_name="单例键"
                    ),
                ),
                (
                    "admin_session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="管理员登录后台后，超过该时间无操作需重新登录。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="后台会话超时(分钟)",
                    ),
                ),
                (
                    "admin_sensitive_action_otp_max_age_seconds",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="超过该时间后，提币审批、Signer 运营等高风险动作需要重新验证两步验证码。",
                        validators=[django.core.validators.MinValueValidator(60)],
                        verbose_name="敏感动作两步验证超时(秒)",
                    ),
                ),
                (
                    "alerts_repeat_interval_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="同一项目同一告警在该时间窗内不重复发送。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="告警重复发送间隔(分钟)",
                    ),
                ),
                (
                    "webhook_delivery_breaker_threshold",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="连续失败达到该次数后，自动关闭项目 Webhook 投递。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 熔断阈值",
                    ),
                ),
                (
                    "webhook_delivery_max_retries",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="单个 Webhook 事件最多自动重试的次数。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 最大重试次数",
                    ),
                ),
                (
                    "webhook_delivery_max_backoff_seconds",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Webhook 自动重试的指数退避上限秒数。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 最大退避秒数",
                    ),
                ),
                (
                    "reviewing_withdrawal_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="审核中提币超过该时间仍未处理时，进入异常巡检。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="审核中提币超时(分钟)",
                    ),
                ),
                (
                    "pending_withdrawal_timeout_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="已批准但仍未进入链上确认流程的提币，超过该时间后进入异常巡检。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="待提币超时(分钟)",
                    ),
                ),
                (
                    "confirming_withdrawal_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="链上确认中提币超过该时间仍未完成时，进入异常巡检。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="确认中提币超时(分钟)",
                    ),
                ),
                (
                    "deposit_collection_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="充币归集超过该时间仍未完成时，进入异常巡检。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="归集超时(分钟)",
                    ),
                ),
                (
                    "webhook_event_timeout_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="待投递 Webhook 事件超过该时间仍未送达时，进入异常巡检。",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Webhook 堆积超时(分钟)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "平台运行参数",
                "verbose_name_plural": "平台运行参数",
            },
        ),
    ]
