# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="open_native_scanner",
            field=models.BooleanField(
                default=False,
                help_text="全局控制 EVM 原生币直转扫描；关闭时 EVM 原生币支付、充币地址和提币入口不可用。",
                verbose_name="开启 EVM 原生币扫描",
            ),
        ),
    ]
