# Generated by Django 5.2.12 on 2026-05-14 02:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_platformsettings_open_native_scanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="quicknode_misttrack_endpoint_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="QuickNode MistTrack add-on 的 JSON-RPC endpoint URL。",
                verbose_name="QuickNode MistTrack Endpoint",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="risk_marking_cache_seconds",
            field=models.PositiveIntegerField(
                default=3600,
                help_text="同一地址风险查询成功后在 Django 缓存中保留的秒数。",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="风险查询缓存秒数",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="risk_marking_enabled",
            field=models.BooleanField(
                default=False,
                help_text="开启后对符合条件的账单和全部充币查询外部地址风险。",
                verbose_name="开启风险标记",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="risk_marking_force_refresh_threshold_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("10000"),
                help_text="本次业务价值大于该阈值时跳过缓存直接查询。",
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="风险查询强制刷新阈值(USD)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="risk_marking_invoice_threshold_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="账单价值大于该阈值时查询风险；充币不受该阈值限制。",
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="账单风险查询阈值(USD)",
            ),
        ),
    ]
