# Generated by Django 5.2.12 on 2026-05-14 02:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_platformsettings_quicknode_misttrack_endpoint_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platformsettings",
            old_name="risk_marking_invoice_threshold_usd",
            new_name="risk_marking_threshold_usd",
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="risk_marking_threshold_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="账单或充币价值大于该阈值时查询风险。",
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="风险查询阈值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="risk_marking_enabled",
            field=models.BooleanField(
                default=False,
                help_text="开启后对高于风险查询阈值的账单和充币查询外部地址风险。",
                verbose_name="开启风险标记",
            ),
        ),
    ]
