# Generated by Django 5.2.12 on 2026-05-14 08:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_risk_marking_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="misttrack_openapi_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MistTrack 官方 OpenAPI API Key；配置后优先使用 V3 风险评分接口。",
                max_length=255,
                verbose_name="MistTrack OpenAPI API Key",
            ),
        ),
    ]
