# Generated by Django 5.2.12 on 2026-05-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="delivery_method",
            field=models.CharField(
                choices=[("post_json", "POST JSON"), ("get_query", "GET Query")],
                default="post_json",
                max_length=16,
                verbose_name="投递方式",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="delivery_url",
            field=models.URLField(blank=True, default="", verbose_name="投递地址"),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="expected_response_body",
            field=models.CharField(
                default="ok", max_length=32, verbose_name="成功响应内容"
            ),
        ),
    ]
