# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_webhookevent_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="delivery_locked_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="投递锁定至",
            ),
        ),
    ]
