# Generated by Django 5.2.12 on 2026-04-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiat",
            fields=[
                (
                    "code",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="代码"
                    ),
                ),
            ],
            options={
                "verbose_name": "法币",
                "verbose_name_plural": "法币",
            },
        ),
        migrations.CreateModel(
            name="ChainToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_index=True, default="", verbose_name="合约地址"
                    ),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="精度覆盖"
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_tokens",
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "代币部署",
                "verbose_name_plural": "代币部署",
            },
        ),
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="名称")),
                (
                    "symbol",
                    models.CharField(
                        help_text="例如:ETH、USDT", unique=True, verbose_name="代码"
                    ),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(default=18, verbose_name="精度"),
                ),
                (
                    "prices",
                    models.JSONField(blank=True, default=dict, verbose_name="价格"),
                ),
                ("coingecko_id", models.CharField(blank=True, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "chains",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cryptos",
                        through="currencies.ChainToken",
                        to="chains.chain",
                        verbose_name="支持的链",
                    ),
                ),
            ],
            options={
                "verbose_name": "加密货币",
                "verbose_name_plural": "加密货币",
            },
        ),
        migrations.AddField(
            model_name="chaintoken",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chain_tokens",
                to="currencies.crypto",
                verbose_name="加密货币",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaintoken",
            constraint=models.UniqueConstraint(
                fields=("crypto", "chain"), name="uniq_chain_token_crypto_chain"
            ),
        ),
        migrations.AddConstraint(
            model_name="chaintoken",
            constraint=models.UniqueConstraint(
                fields=("chain", "address"), name="uniq_chain_token_chain_address"
            ),
        ),
    ]
