# Generated by Django 5.2.12 on 2026-04-09 14:13

import common.fields
import shortuuid.django_fields
import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "appid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="23456789ABCDEFGHJKLMNPQRSTUVWXYZ",
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=11,
                        prefix="XC-",
                        verbose_name="Appid",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="对外作为商户名展示",
                        verbose_name="项目名称",
                    ),
                ),
                (
                    "ip_white_list",
                    models.TextField(
                        help_text="只有符合白名单的 IP 才可以与本网关交互，支持 IP 地址或 IP 网段<br>可同时设置多个，中间用英文逗号 ',' 分割<br>* 代表允许所有 IP 访问",
                        verbose_name="IP白名单",
                    ),
                ),
                (
                    "webhook",
                    models.URLField(
                        help_text="用于本网关发送通知到项目后端",
                        verbose_name="通知地址",
                    ),
                ),
                (
                    "webhook_open",
                    models.BooleanField(default=True, verbose_name="通知状态"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="连续失败次数"),
                ),
                (
                    "pre_notify",
                    models.BooleanField(
                        default=False,
                        help_text="刚出块(尚未达到区块确认数)，就发送一次预通知",
                        verbose_name="开启预通知",
                    ),
                ),
                (
                    "fast_confirm_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="低于该金额的账单无需等待，立即确认",
                        max_digits=10,
                        verbose_name="快速确认阈值（USD）",
                    ),
                ),
                (
                    "hmac_key",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=32,
                        max_length=32,
                        prefix="",
                        verbose_name="HMAC密钥",
                    ),
                ),
                (
                    "gather_worth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=10,
                        help_text="某充币地址中,若某代币的价值大于此,则自动归集",
                        max_digits=16,
                        verbose_name="自动归集价值(USD)",
                    ),
                ),
                (
                    "gather_period",
                    models.PositiveIntegerField(
                        blank=True,
                        default=32,
                        help_text="某充币地址中,若某代币大于此周期未进行归集操作,则自动归集",
                        verbose_name="自动归集周期(日)",
                    ),
                ),
                (
                    "withdrawal_review_required",
                    models.BooleanField(
                        default=True,
                        help_text="开启后，新提币请求会先进入审核中，需后台批准后才会进入链上发送队列",
                        verbose_name="提币需审核",
                    ),
                ),
                (
                    "withdrawal_review_exempt_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="仅在开启提币审核时生效；低于该金额的提币可直接进入链上发送队列，留空表示全部需要审核",
                        max_digits=16,
                        null=True,
                        verbose_name="免审核门槛(USD)",
                    ),
                ),
                (
                    "withdrawal_single_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="留空表示不限额；超出时直接拒绝创建提币请求",
                        max_digits=16,
                        null=True,
                        verbose_name="单笔提币限额(USD)",
                    ),
                ),
                (
                    "withdrawal_daily_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="留空表示不限额；当天已创建的提币请求也会占用额度",
                        max_digits=16,
                        null=True,
                        verbose_name="单日提币限额(USD)",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 项目",
                "verbose_name_plural": "historical 项目",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRecipientAddress",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(verbose_name="名称")),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("btc", "Bitcoin")],
                        help_text="EVM: Ethereum, BSC, Polygon, Base...<br>Bitcoin: Bitcoin",
                        verbose_name="地址格式",
                    ),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="收币地址"
                    ),
                ),
                (
                    "used_for_invoice",
                    models.BooleanField(default=True, verbose_name="用于账单收款"),
                ),
                (
                    "used_for_deposit",
                    models.BooleanField(default=False, verbose_name="用于归集充币"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 收币地址",
                "verbose_name_plural": "historical 收币地址",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="23456789ABCDEFGHJKLMNPQRSTUVWXYZ",
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=11,
                        prefix="XC-",
                        unique=True,
                        verbose_name="Appid",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="对外作为商户名展示",
                        unique=True,
                        verbose_name="项目名称",
                    ),
                ),
                (
                    "ip_white_list",
                    models.TextField(
                        help_text="只有符合白名单的 IP 才可以与本网关交互，支持 IP 地址或 IP 网段<br>可同时设置多个，中间用英文逗号 ',' 分割<br>* 代表允许所有 IP 访问",
                        verbose_name="IP白名单",
                    ),
                ),
                (
                    "webhook",
                    models.URLField(
                        help_text="用于本网关发送通知到项目后端",
                        verbose_name="通知地址",
                    ),
                ),
                (
                    "webhook_open",
                    models.BooleanField(default=True, verbose_name="通知状态"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="连续失败次数"),
                ),
                (
                    "pre_notify",
                    models.BooleanField(
                        default=False,
                        help_text="刚出块(尚未达到区块确认数)，就发送一次预通知",
                        verbose_name="开启预通知",
                    ),
                ),
                (
                    "fast_confirm_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="低于该金额的账单无需等待，立即确认",
                        max_digits=10,
                        verbose_name="快速确认阈值（USD）",
                    ),
                ),
                (
                    "hmac_key",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=32,
                        max_length=32,
                        prefix="",
                        verbose_name="HMAC密钥",
                    ),
                ),
                (
                    "gather_worth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=10,
                        help_text="某充币地址中,若某代币的价值大于此,则自动归集",
                        max_digits=16,
                        verbose_name="自动归集价值(USD)",
                    ),
                ),
                (
                    "gather_period",
                    models.PositiveIntegerField(
                        blank=True,
                        default=32,
                        help_text="某充币地址中,若某代币大于此周期未进行归集操作,则自动归集",
                        verbose_name="自动归集周期(日)",
                    ),
                ),
                (
                    "withdrawal_review_required",
                    models.BooleanField(
                        default=True,
                        help_text="开启后，新提币请求会先进入审核中，需后台批准后才会进入链上发送队列",
                        verbose_name="提币需审核",
                    ),
                ),
                (
                    "withdrawal_review_exempt_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="仅在开启提币审核时生效；低于该金额的提币可直接进入链上发送队列，留空表示全部需要审核",
                        max_digits=16,
                        null=True,
                        verbose_name="免审核门槛(USD)",
                    ),
                ),
                (
                    "withdrawal_single_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="留空表示不限额；超出时直接拒绝创建提币请求",
                        max_digits=16,
                        null=True,
                        verbose_name="单笔提币限额(USD)",
                    ),
                ),
                (
                    "withdrawal_daily_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="留空表示不限额；当天已创建的提币请求也会占用额度",
                        max_digits=16,
                        null=True,
                        verbose_name="单日提币限额(USD)",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
            },
        ),
        migrations.CreateModel(
            name="RecipientAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="名称")),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("btc", "Bitcoin")],
                        help_text="EVM: Ethereum, BSC, Polygon, Base...<br>Bitcoin: Bitcoin",
                        verbose_name="地址格式",
                    ),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="收币地址"
                    ),
                ),
                (
                    "used_for_invoice",
                    models.BooleanField(default=True, verbose_name="用于账单收款"),
                ),
                (
                    "used_for_deposit",
                    models.BooleanField(default=False, verbose_name="用于归集充币"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "收币地址",
                "verbose_name_plural": "收币地址",
            },
        ),
    ]
