# Generated by Django 5.2.12 on 2026-04-19 13:00

from django.db import migrations
from django.db import models


def forwards_convert_gather_period_days_to_minutes(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().iterator():
        project.gather_period = project.gather_period * 1440
        project.save(update_fields=["gather_period"])


def backwards_convert_gather_period_minutes_to_days(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().iterator():
        project.gather_period = max(1, project.gather_period // 1440)
        project.save(update_fields=["gather_period"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            forwards_convert_gather_period_days_to_minutes,
            backwards_convert_gather_period_minutes_to_days,
        ),
        migrations.AlterField(
            model_name="project",
            name="gather_worth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                help_text="归集窗口到期时, 若某充币地址下该代币待归集总价值达到此阈值, 则自动归集",
                max_digits=16,
                verbose_name="自动归集价值(USD)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gather_period",
            field=models.PositiveIntegerField(
                blank=True,
                default=1440,
                help_text="某充币地址中,若某代币在此周期内未归集,则到期尝试归集",
                verbose_name="自动归集周期(分钟)",
            ),
        ),
    ]
