# Generated by Django 5.2.12 on 2026-04-13 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="chains.wallet",
            ),
        ),
        migrations.AddField(
            model_name="historicalrecipientaddress",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="wallet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chains.wallet"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecipientaddress",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.AddField(
            model_name="recipientaddress",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipientaddress",
            constraint=models.UniqueConstraint(
                fields=("chain_type", "address"),
                name="uniq_recipient_address_chain_type_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipientaddress",
            constraint=models.CheckConstraint(
                condition=models.Q(("usage__in", ("invoice", "deposit_collection"))),
                name="recipient_address_valid_usage",
            ),
        ),
    ]
