# Generated by Django 5.2.12 on 2026-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecipientaddress",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("btc", "Bitcoin"), ("tron", "Tron")],
                help_text="EVM: Ethereum, BSC, Polygon, Base...<br>Bitcoin: Bitcoin",
                verbose_name="地址格式",
            ),
        ),
        migrations.AlterField(
            model_name="recipientaddress",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("btc", "Bitcoin"), ("tron", "Tron")],
                help_text="EVM: Ethereum, BSC, Polygon, Base...<br>Bitcoin: Bitcoin",
                verbose_name="地址格式",
            ),
        ),
    ]
