# Generated by Django 5.2.12 on 2026-04-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_historicalrecipientaddress_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="webhook",
            field=models.URLField(
                blank=True,
                default="",
                help_text="用于本网关发送通知到项目后端",
                verbose_name="通知地址",
            ),
        ),
    ]
