# Generated by Django 5.2.12 on 2026-04-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_simple_history_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ip_white_list",
            field=models.TextField(
                default="*",
                help_text="只有符合白名单的 IP 才可以与本网关交互，支持 IP 地址或 IP 网段<br>可同时设置多个，中间用英文逗号 ',' 分割<br>* 代表允许所有 IP 访问",
                verbose_name="IP白名单",
            ),
        ),
    ]
