# Generated by Django 5.2.12 on 2026-05-14 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deposits", "0005_deposit_risk_level_deposit_risk_score"),
        ("invoices", "0011_invoice_risk_level_invoice_risk_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("quicknode_misttrack", "QuickNode MistTrack")],
                        db_index=True,
                        default="quicknode_misttrack",
                        max_length=32,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待查询"),
                            ("success", "查询成功"),
                            ("failed", "查询失败"),
                            ("skipped", "已跳过"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="查询状态",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("invoice", "账单"), ("deposit", "充币")],
                        db_index=True,
                        max_length=16,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="查询地址"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="交易哈希"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                            ("Severe", "Severe"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="风险分数",
                    ),
                ),
                (
                    "detail_list",
                    models.JSONField(
                        blank=True, default=list, verbose_name="风险原因列表"
                    ),
                ),
                (
                    "risk_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="风险详情"),
                ),
                (
                    "risk_report_url",
                    models.URLField(
                        blank=True, default="", verbose_name="风险报告链接"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="原始响应摘要"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误摘要"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="查询完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deposit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="deposits.deposit",
                        verbose_name="充币",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="invoices.invoice",
                        verbose_name="账单",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险评估",
                "verbose_name_plural": "风险评估",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("invoice__isnull", False), ("deposit__isnull", True)
                            ),
                            models.Q(
                                ("invoice__isnull", True), ("deposit__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="risk_assessment_exactly_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_type", "invoice"),
                                ("invoice__isnull", False),
                                ("deposit__isnull", True),
                            ),
                            models.Q(
                                ("target_type", "deposit"),
                                ("invoice__isnull", True),
                                ("deposit__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="risk_assessment_target_type_matches_target",
                    ),
                ],
            },
        ),
    ]
