# Generated by Django 5.2.12 on 2026-05-14 08:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessment",
            name="source",
            field=models.CharField(
                choices=[
                    ("quicknode_misttrack", "QuickNode MistTrack"),
                    ("misttrack_openapi", "MistTrack OpenAPI"),
                ],
                db_index=True,
                default="quicknode_misttrack",
                max_length=32,
                verbose_name="数据来源",
            ),
        ),
    ]
