# Generated by Django 5.2.12 on 2026-04-05 13:23

import django.db.models.deletion
import django.utils.timezone
import users.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "此用户名已被使用."},
                        max_length=150,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="用户名快照",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("password_login", "密码登录"),
                            ("otp_verify", "两步验证校验"),
                            ("otp_setup", "两步验证绑定"),
                            ("otp_rotate", "两步验证修改"),
                            ("logout", "退出登录"),
                        ],
                        max_length=32,
                        verbose_name="动作",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("succeeded", "成功"), ("failed", "失败")],
                        max_length=16,
                        verbose_name="结果",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台访问日志",
                "verbose_name_plural": "后台访问日志",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, verbose_name="客户UID")),
                ("address_index", models.BigIntegerField(editable=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uid", "project"), name="uniq_customer_uid_project"
                    ),
                    models.UniqueConstraint(
                        fields=("address_index", "project"),
                        name="uniq_customer_address_index_project",
                    ),
                ],
            },
        ),
    ]
