# Generated by Django 5.2.12 on 2026-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositstresscase",
            name="api_done_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="获取充值地址完成时间"
            ),
        ),
        migrations.AddField(
            model_name="depositstresscase",
            name="chain_paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="链上充值完成时间"
            ),
        ),
        migrations.AddField(
            model_name="depositstresscase",
            name="collection_done_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="归集完成时间"
            ),
        ),
        migrations.AddField(
            model_name="depositstresscase",
            name="webhook_received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Webhook 处理完成时间"
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="api_done_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="选支付方式完成时间"
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="chain_paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="链上广播完成时间"
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="invoice_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="账单创建完成时间"
            ),
        ),
        migrations.AddField(
            model_name="invoicestresscase",
            name="webhook_received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Webhook 处理完成时间"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalstresscase",
            name="api_done_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="提币 API 完成时间"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalstresscase",
            name="webhook_received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Webhook 处理完成时间"
            ),
        ),
    ]
