# Generated by Django 5.2.12 on 2026-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitcoinScanCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_scanned_block",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描到的区块"
                    ),
                ),
                (
                    "last_safe_block",
                    models.PositiveIntegerField(default=0, verbose_name="安全区块"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_error",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="最近错误"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近错误时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Bitcoin 扫描游标",
                "verbose_name_plural": "Bitcoin 扫描游标",
                "ordering": ("chain_id",),
            },
        ),
    ]
