# Generated by Django 5.2.12 on 2026-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitcoinBroadcastTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signed_payload", models.TextField(verbose_name="已签名链上载荷")),
                (
                    "fee_satoshi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="矿工费（satoshi）"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次尝试时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Bitcoin 链上任务",
                "verbose_name_plural": "Bitcoin 链上任务",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="BitcoinReservedUtxo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.CharField(max_length=64, verbose_name="UTXO 交易哈希")),
                ("vout", models.PositiveIntegerField(verbose_name="UTXO 输出序号")),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="释放时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Bitcoin 预留 UTXO",
                "verbose_name_plural": "Bitcoin 预留 UTXO",
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="BitcoinScanCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_scanned_block",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描到的区块"
                    ),
                ),
                (
                    "last_safe_block",
                    models.PositiveIntegerField(default=0, verbose_name="安全区块"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_error",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="最近错误"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近错误时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Bitcoin 扫描游标",
                "verbose_name_plural": "Bitcoin 扫描游标",
                "ordering": ("chain_id",),
            },
        ),
    ]
