# Generated by Django 5.2.12 on 2026-04-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bitcoin", "0001_initial"),
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitcoinscancursor",
            name="chain",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bitcoin_scan_cursor",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
    ]
