# Generated by Django 5.2.12 on 2026-04-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bitcoin", "0001_initial"),
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitcoinbroadcasttask",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.address",
                verbose_name="地址",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinbroadcasttask",
            name="base_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bitcoin_task",
                to="chains.broadcasttask",
                verbose_name="通用链上任务",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinbroadcasttask",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.chain",
                verbose_name="网络",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinreservedutxo",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_bitcoin_utxos",
                to="chains.address",
                verbose_name="地址",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinreservedutxo",
            name="broadcast_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_utxos",
                to="chains.broadcasttask",
                verbose_name="链上任务",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinreservedutxo",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_bitcoin_utxos",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="bitcoinscancursor",
            name="chain",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bitcoin_scan_cursor",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddConstraint(
            model_name="bitcoinreservedutxo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("chain", "txid", "vout"),
                name="uniq_bitcoin_reserved_utxo_active",
            ),
        ),
    ]
