"""MistTrack OpenAPI / QuickNode add-on 的 chain & coin 取值映射。

仅整理静态常量映射，不依赖项目其他模型，便于按官方文档维护：
- QuickNode add-on 当前仅支持 Bitcoin、Tron、Ethereum、BNB Smart Chain、Arbitrum。
- MistTrack OpenAPI V3 的 coin 取值见
  https://docs.misttrack.io/openapi/overview#multi-chain-support
"""

from __future__ import annotations

# QuickNode add-on 支持的 EVM 链 → mt_addressRiskScore 的 chain 参数取值
QUICKNODE_EVM_CHAIN: dict[int, str] = {
    1: "ETH",
    56: "BNB",
    42161: "ARBITRUM",
}

# MistTrack OpenAPI V3：Tron 链上 symbol → coin
OPENAPI_TRON_COIN: dict[str, str] = {
    "TRX": "TRX",
    "USDT": "USDT-TRC20",
    "USDC": "USDC-TRC20",
    "USDD": "USDD-TRC20",
}

# MistTrack OpenAPI V3：EVM 链 chain_id → {symbol: coin}
OPENAPI_EVM_COIN: dict[int, dict[str, str]] = {
    1: {
        "ETH": "ETH",
        "USDT": "USDT-ERC20",
        "USDC": "USDC-ERC20",
        "WETH": "WETH-ERC20",
        "BNB": "BNB-ERC20",
        "UNI": "UNI-ERC20",
        "BUSD": "BUSD-ERC20",
        "DAI": "DAI-ERC20",
        "GRT": "GRT-ERC20",
        "ENS": "ENS-ERC20",
        "UST": "UST-ERC20",
        "RENBTC": "renBTC-ERC20",
        "WBTC": "WBTC-ERC20",
        "TUSD": "TUSD-ERC20",
        "SHIB": "SHIB-ERC20",
        "LINK": "LINK-ERC20",
        "BAT": "BAT-ERC20",
        "CRO": "CRO-ERC20",
        "SUSHI": "SUSHI-ERC20",
        "STETH": "stETH-ERC20",
        "CRV": "CRV-ERC20",
        "CVX": "CVX-ERC20",
        "CVXCRV": "cvxCRV-ERC20",
        "3CRV": "3Crv-ERC20",
        "LOOKS": "LOOKS-ERC20",
        "IOTX": "IOTX-ERC20",
        "APE": "APE-ERC20",
        "PYUSD": "PYUSD-ERC20",
        "MEME": "MEME-ERC20",
        "WUSD": "WUSD-ERC20",
        "PEPE": "PEPE-ERC20",
        "CBBTC": "cbBTC-ERC20",
        "FLOKI": "FLOKI-ERC20",
        "LEO": "LEO-ERC20",
        "USDS": "USDS-ERC20",
        "FDUSD": "FDUSD-ERC20",
        "USDE": "USDe-ERC20",
        "USD1": "USD1-ERC20",
        "WLFI": "WLFI-ERC20",
        "SUSD": "sUSD-ERC20",
    },
    10: {
        "ETH": "ETH-Optimism",
        "USDT": "USDT-Optimism",
        "USDC": "USDC-Optimism",
        "USDC.E": "USDC.e-Optimism",
        "OP": "OP-Optimism",
        "DAI": "DAI-Optimism",
        "WBTC": "WBTC-Optimism",
        "WETH": "WETH-Optimism",
        "SNX": "SNX-Optimism",
        "SUSD": "sUSD-Optimism",
        "VELO": "VELO-Optimism",
        "WLD": "WLD-Optimism",
        "USDE": "USDe-Optimism",
    },
    56: {
        "BNB": "BNB",
        "BUSD": "BUSD-BEP20",
        "USDT": "USDT-BEP20",
        "WBNB": "WBNB-BEP20",
        "ETH": "ETH-BEP20",
        "BTCB": "BTCB-BEP20",
        "DOGE": "DOGE-BEP20",
        "USDC": "USDC-BEP20",
        "SHIB": "SHIB-BEP20",
        "UST": "UST-BEP20",
        "DAI": "DAI-BEP20",
        "CAKE": "Cake-BEP20",
        "BCH": "BCH-BEP20",
        "USD1": "USD1-BEP20",
        "TUSD": "TUSD-BEP20",
        "USDE": "USDe-BEP20",
        "FDUSD": "FDUSD-BEP20",
    },
    137: {
        "POL": "POL-Polygon",
        "WMATIC": "WMATIC-Polygon",
        "WETH": "WETH-Polygon",
        "USDC": "USDC-Polygon",
        "USDC.E": "USDC.e-Polygon",
        "USDT": "USDT-Polygon",
        "DAI": "DAI-Polygon",
        "WBTC": "WBTC-Polygon",
        "AAVE": "AAVE-Polygon",
        "LINK": "LINK-Polygon",
        "UNI": "UNI-Polygon",
        "UST": "UST-Polygon",
        "SUSHI": "SUSHI-Polygon",
        "WUSD": "WUSD-Polygon",
        "BUSD": "BUSD-Polygon",
    },
    324: {
        "ETH": "ETH-zkSync",
        "ZK": "ZK-zkSync",
        "USDT": "USDT-zkSync",
        "USDC": "USDC-zkSync",
    },
    4200: {"BTC": "BTC-Merlin"},
    4689: {"IOTX": "IOTX"},
    8453: {
        "ETH": "ETH-Base",
        "USDC": "USDC-Base",
        "USDBC": "USDbC-Base",
        "WETH": "WETH-Base",
        "DEGEN": "DEGEN-Base",
        "DAI": "DAI-Base",
        "CBETH": "cbETH-Base",
        "USDT": "USDT-Base",
        "WBTC": "WBTC-Base",
        "USDS": "USDS-Base",
        "WSTETH": "wstETH-Base",
        "USDE": "USDe-Base",
        "LINK": "LINK-Base",
        "CBBTC": "cbBTC-Base",
        "AAVE": "AAVE-Base",
        "LBTC": "LBTC-Base",
        "OM": "OM-Base",
        "RETH": "rETH-Base",
        "CRV": "CRV-Base",
        "SOLVBTC": "SolvBTC-Base",
    },
    42161: {
        "ETH": "ETH-Arbitrum",
        "USDT": "USDT-Arbitrum",
        "USDC": "USDC-Arbitrum",
        "USDC.E": "USDC.e-Arbitrum",
        "WETH": "WETH-Arbitrum",
        "DAI": "DAI-Arbitrum",
        "WBTC": "WBTC-Arbitrum",
        "LINK": "LINK-Arbitrum",
        "GMX": "GMX-Arbitrum",
        "SBFGMX": "sbfGMX-Arbitrum",
        "STG": "STG-Arbitrum",
        "MAGIC": "MAGIC-Arbitrum",
        "ARB": "ARB-Arbitrum",
        "USDS": "USDS-Arbitrum",
        "USDE": "USDe-Arbitrum",
        "FDUSD": "FDUSD-Arbitrum",
    },
    43114: {
        "AVAX": "AVAX-Avalanche",
        "WAVAX": "WAVAX-Avalanche",
        "BTC.B": "BTC.b-Avalanche",
        "USDT": "USDT-Avalanche",
        "USDT.E": "USDT.e-Avalanche",
        "USDC": "USDC-Avalanche",
        "USDC.E": "USDC.e-Avalanche",
        "WETH.E": "WETH.e-Avalanche",
        "DAI.E": "DAI.e-Avalanche",
        "WBTC.E": "WBTC.e-Avalanche",
    },
}
