# Generated by Django 5.2.12 on 2026-04-05 13:23

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sys_no",
                    common.fields.SysNoField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=32,
                        prefix="DXC",
                        unique=True,
                        verbose_name="系统单号",
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirming", "确认中"),
                            ("completed", "已完成"),
                            ("dropped", "丢弃"),
                        ],
                        default="confirming",
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "充币",
                "verbose_name_plural": "充币",
            },
        ),
        migrations.CreateModel(
            name="DepositAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("btc", "Bitcoin")],
                        verbose_name="链类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "充币地址",
                "verbose_name_plural": "充币地址",
            },
        ),
        migrations.CreateModel(
            name="DepositCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection_hash",
                    common.fields.HashField(
                        blank=True,
                        db_index=True,
                        max_length=66,
                        null=True,
                        unique=True,
                        verbose_name="归集哈希",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归集确认时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "归集记录",
                "verbose_name_plural": "归集记录",
            },
        ),
    ]
