# Generated by Django 5.2.12 on 2026-04-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("deposits", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="transfer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chains.onchaintransfer",
                verbose_name="链上转账",
            ),
        ),
        migrations.AddField(
            model_name="depositaddress",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.address",
                verbose_name="地址",
            ),
        ),
        migrations.AddField(
            model_name="depositaddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AddField(
            model_name="depositcollection",
            name="broadcast_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_collection",
                to="chains.broadcasttask",
                verbose_name="链上任务",
            ),
        ),
        migrations.AddField(
            model_name="depositcollection",
            name="transfer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_collection",
                to="chains.onchaintransfer",
                verbose_name="归集转账",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposits",
                to="deposits.depositcollection",
                verbose_name="归集记录",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositaddress",
            constraint=models.UniqueConstraint(
                fields=("customer", "chain_type"),
                name="uniq_deposit_address_customer_chain_type",
            ),
        ),
    ]
