# Generated by Django 5.2.12 on 2026-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositaddress",
            name="chain_type",
            field=models.CharField(
                choices=[("evm", "EVM"), ("btc", "Bitcoin"), ("tron", "Tron")],
                verbose_name="链类型",
            ),
        ),
    ]
