# Generated by Django 5.2.12 on 2026-04-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0002_initial"),
        ("currencies", "0001_initial"),
        ("deposits", "0003_deposit_failed_collection_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "next_collect_time",
                    models.DateTimeField(db_index=True, verbose_name="下次归集时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.crypto",
                        verbose_name="代币",
                    ),
                ),
                (
                    "deposit_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collect_schedules",
                        to="deposits.depositaddress",
                        verbose_name="充币地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "归集调度",
                "verbose_name_plural": "归集调度",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deposit_address", "chain", "crypto"),
                        name="uniq_collect_schedule_address_chain_crypto",
                    ),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="failed_collection_attempts",
        ),
    ]
