# Generated by Django 5.2.12 on 2026-04-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0003_alter_address_chain_type_alter_chain_type"),
        ("deposits", "0004_deposit_transfer_non_nullable_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recharged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="到账时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gas_recharge",
                        to="chains.broadcasttask",
                        verbose_name="链上任务",
                    ),
                ),
                (
                    "deposit_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gas_recharges",
                        to="deposits.depositaddress",
                        verbose_name="充币地址",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gas_recharge",
                        to="chains.onchaintransfer",
                        verbose_name="链上转账",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gas 补充",
                "verbose_name_plural": "Gas 补充",
            },
        ),
    ]
