# 生产环境 Bitcoin Core 配置（mainnet pruned）
# 裁剪节点只保留最近 550 MB 区块数据（约 2 天），仅供 Invoice 支付扫描。

server=1
prune=550

[main]
rpcbind=0.0.0.0
rpcallowip=172.16.0.0/12
rpcport=8332
rpcuser=xcash
rpcpassword=xcash
