# Generated by Django 5.2.12 on 2026-04-17 06:35

import common.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("btc", "Bitcoin"), ("tron", "Tron")],
                        verbose_name="链类型",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[("deposit", "充币帐户"), ("vault", "金库账户")],
                        verbose_name="用途",
                    ),
                ),
                (
                    "bip44_account",
                    models.PositiveIntegerField(verbose_name="BIP44 账户层级"),
                ),
                (
                    "address_index",
                    models.PositiveIntegerField(default=0, verbose_name="地址索引"),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, unique=True, verbose_name="地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "地址",
                "verbose_name_plural": "地址",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BroadcastTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("iv", "💳 支付"),
                            ("deposit", "💰 充币"),
                            ("withdrawal", "🏧 提币"),
                            ("gas-recharge", "⛽ Gas分发"),
                            ("deposit-collection", "💵 归集充币"),
                            ("prefunding", "🏦 注入金库资金"),
                        ],
                        verbose_name="类型",
                    ),
                ),
                (
                    "recipient",
                    common.fields.AddressField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="收款地址",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=48,
                        null=True,
                        verbose_name="数量",
                    ),
                ),
                (
                    "tx_hash",
                    common.fields.HashField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=False,
                        verbose_name="交易哈希",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("queued", "待广播"),
                            ("pending_chain", "待上链"),
                            ("pending_confirm", "确认中"),
                            ("finalized", "已终结"),
                        ],
                        default="queued",
                        verbose_name="阶段",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("unknown", "未知"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="unknown",
                        verbose_name="结果",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rpc_rejected", "节点拒绝"),
                            ("insufficient_balance", "余额不足"),
                            ("fee_too_low", "手续费过低"),
                            ("execution_reverted", "链上执行回退"),
                            ("utxo_conflict", "UTXO 冲突"),
                            ("double_spend", "双花冲突"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="失败原因",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "链上任务",
                "verbose_name_plural": "链上任务",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="名称")),
                ("code", models.CharField(unique=True, verbose_name="代码")),
                (
                    "type",
                    models.CharField(
                        choices=[("evm", "EVM"), ("btc", "Bitcoin"), ("tron", "Tron")],
                        verbose_name="类型",
                    ),
                ),
                (
                    "confirm_block_count",
                    models.PositiveIntegerField(default=10, verbose_name="区块确认数"),
                ),
                (
                    "latest_block_number",
                    models.PositiveIntegerField(default=0, verbose_name="最新区块"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="启用")),
                (
                    "base_transfer_gas",
                    models.PositiveIntegerField(
                        default=50000,
                        help_text="原生币（ETH/BNB 等）转账的 gas 上限",
                        verbose_name="原生币转账 Gas Limit",
                    ),
                ),
                (
                    "erc20_transfer_gas",
                    models.PositiveIntegerField(
                        default=100000,
                        help_text="ERC-20 代币 transfer 调用的 gas 上限",
                        verbose_name="ERC20 转账 Gas Limit",
                    ),
                ),
                (
                    "chain_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Chain ID"
                    ),
                ),
                ("rpc", models.CharField(blank=True, default="", verbose_name="RPC")),
                (
                    "is_poa",
                    models.BooleanField(blank=True, null=True, verbose_name="POA"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "链",
                "verbose_name_plural": "链",
            },
        ),
        migrations.CreateModel(
            name="OnchainTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block", models.IntegerField(verbose_name="区块")),
                (
                    "hash",
                    common.fields.HashField(
                        db_index=True, max_length=100, unique=False, verbose_name="哈希"
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="事件标识",
                    ),
                ),
                (
                    "from_address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="发送地址"
                    ),
                ),
                (
                    "to_address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="目的地址"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=32, verbose_name="数值"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="数量"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("iv", "💳 支付"),
                            ("deposit", "💰 充币"),
                            ("withdrawal", "🏧 提币"),
                            ("gas-recharge", "⛽ Gas分发"),
                            ("deposit-collection", "💵 归集充币"),
                            ("prefunding", "🏦 注入金库资金"),
                        ],
                        default="",
                        verbose_name="类型",
                    ),
                ),
                (
                    "confirm_mode",
                    models.CharField(
                        choices=[("full", "完全"), ("quick", "快速")],
                        default="full",
                        max_length=8,
                        verbose_name="确认模式",
                    ),
                ),
                (
                    "timestamp",
                    models.PositiveIntegerField(db_index=True, verbose_name="时间戳"),
                ),
                ("datetime", models.DateTimeField(verbose_name="日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("confirming", "确认中"), ("confirmed", "已确认")],
                        default="confirming",
                        verbose_name="状态",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "转账",
                "verbose_name_plural": "转账",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="TxHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    common.fields.HashField(
                        db_index=True,
                        max_length=100,
                        unique=False,
                        verbose_name="交易哈希",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "交易哈希历史",
                "verbose_name_plural": "交易哈希历史",
                "ordering": ("broadcast_task_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
            },
        ),
        migrations.CreateModel(
            name="AddressChainState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "next_nonce",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="下一个 nonce"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_states",
                        to="chains.address",
                        verbose_name="地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "地址链状态",
                "verbose_name_plural": "地址链状态",
            },
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=48,
                        verbose_name="原始余额",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=30,
                        default=Decimal("0"),
                        max_digits=50,
                        verbose_name="余额",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="chains.address",
                        verbose_name="地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "余额",
                "verbose_name_plural": "余额",
            },
        ),
    ]
