# Generated by Django 5.2.12 on 2026-04-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="chain_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="currencies.chaintoken",
                verbose_name="代币部署",
            ),
        ),
        migrations.AddField(
            model_name="broadcasttask",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.address",
                verbose_name="地址",
            ),
        ),
        migrations.AddField(
            model_name="broadcasttask",
            name="crypto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="currencies.crypto",
                verbose_name="代币",
            ),
        ),
        migrations.AddField(
            model_name="chain",
            name="native_coin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chains_as_native_coin",
                to="currencies.crypto",
                verbose_name="原生币",
            ),
        ),
        migrations.AddField(
            model_name="broadcasttask",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="addresschainstate",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_states",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="onchaintransfer",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="onchaintransfer",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="currencies.crypto",
                verbose_name="加密货币",
            ),
        ),
        migrations.AddField(
            model_name="txhash",
            name="broadcast_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tx_hashes",
                to="chains.broadcasttask",
                verbose_name="链上任务",
            ),
        ),
        migrations.AddField(
            model_name="txhash",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tx_hashes",
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.wallet",
                verbose_name="钱包",
            ),
        ),
        migrations.AddConstraint(
            model_name="balance",
            constraint=models.UniqueConstraint(
                fields=("address", "chain_token"),
                name="uniq_balance_address_chain_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcasttask",
            constraint=models.UniqueConstraint(
                fields=("chain", "tx_hash"), name="uniq_broadcast_task_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcasttask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result", "unknown"), ("stage", "finalized"), _connector="OR"
                ),
                name="ck_broadcast_task_result_requires_finalized_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcasttask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("stage", "finalized"), _negated=True),
                    models.Q(("result", "unknown"), _negated=True),
                    _connector="OR",
                ),
                name="ck_broadcast_task_finalized_requires_known_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcasttask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("result", "failed"),
                        models.Q(("failure_reason", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("result", "failed"), _negated=True),
                        ("failure_reason", ""),
                    ),
                    _connector="OR",
                ),
                name="ck_broadcast_task_failure_reason_matches_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="addresschainstate",
            constraint=models.UniqueConstraint(
                fields=("address", "chain"),
                name="uniq_address_chain_state_address_chain",
            ),
        ),
        migrations.AddConstraint(
            model_name="onchaintransfer",
            constraint=models.UniqueConstraint(
                fields=("chain", "hash", "event_id"),
                name="uniq_transfer_chain_hash_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="txhash",
            constraint=models.UniqueConstraint(
                fields=("chain", "hash"), name="uniq_tx_hash_chain_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="txhash",
            constraint=models.UniqueConstraint(
                fields=("broadcast_task", "version"), name="uniq_tx_hash_task_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("wallet", "chain_type", "usage", "address_index"),
                name="uniq_address_wallet_chain_usage_addridx",
            ),
        ),
    ]
