# Generated by Codex on 2026-05-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0006_chain_tron_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chain",
            name="open_native_scanner",
        ),
    ]
