# Generated by Django 5.2.12 on 2026-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0007_remove_chain_open_native_scanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onchaintransfer",
            name="confirm_mode",
            field=models.CharField(
                choices=[("full", "完全"), ("quick", "快速")],
                default="full",
                help_text="当前仅 Invoice 业务根据 fast_confirm_threshold 动态设置 QUICK/FULL；Deposit 与 Withdrawal 始终使用默认 FULL，走完整区块确认流程。",
                max_length=8,
                verbose_name="确认模式",
            ),
        ),
    ]
