# Generated by Django 5.2.12 on 2026-04-13 12:48

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvmBroadcastTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.PositiveBigIntegerField(verbose_name="Nonce")),
                (
                    "to",
                    common.fields.EvmAddressField(
                        db_index=True, max_length=42, verbose_name="To"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=32, verbose_name="Value"
                    ),
                ),
                ("data", models.TextField(blank=True, default="", verbose_name="Data")),
                ("gas", models.PositiveIntegerField(verbose_name="Gas")),
                (
                    "gas_price",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Gas Price"
                    ),
                ),
                (
                    "signed_payload",
                    models.TextField(
                        blank=True, default="", verbose_name="已签名链上载荷"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次尝试时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.address",
                        verbose_name="地址",
                    ),
                ),
                (
                    "base_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evm_task",
                        to="chains.broadcasttask",
                        verbose_name="通用链上任务",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.chain",
                        verbose_name="网络",
                    ),
                ),
            ],
            options={
                "verbose_name": "链上任务",
                "verbose_name_plural": "链上任务",
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("address", "chain", "nonce"),
                        name="uniq_evm_broadcast_task_address_chain_nonce",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvmScanCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanner_type",
                    models.CharField(
                        choices=[
                            ("native_direct", "原生币直转"),
                            ("erc20_transfer", "ERC20 转账"),
                        ],
                        max_length=32,
                        verbose_name="扫描器类型",
                    ),
                ),
                (
                    "last_scanned_block",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描到的区块"
                    ),
                ),
                (
                    "last_safe_block",
                    models.PositiveIntegerField(default=0, verbose_name="安全区块"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_error",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="最近错误"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近错误时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evm_scan_cursors",
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVM 扫描游标",
                "verbose_name_plural": "EVM 扫描游标",
                "ordering": ("chain_id", "scanner_type"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain", "scanner_type"),
                        name="uniq_evm_scan_cursor_chain_scanner_type",
                    )
                ],
            },
        ),
    ]
