# Generated by Django 5.2.12 on 2026-04-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectAlertState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("withdrawal_stalled", "提币卡单"),
                            ("deposit_collection_stalled", "归集卡单"),
                            ("webhook_stalled", "Webhook 堆积"),
                        ],
                        max_length=64,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(max_length=32, verbose_name="对象类型"),
                ),
                ("object_pk", models.PositiveBigIntegerField(verbose_name="对象 ID")),
                (
                    "fingerprint",
                    models.CharField(max_length=128, unique=True, verbose_name="指纹"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "严重"),
                            ("high", "高"),
                            ("medium", "中"),
                        ],
                        max_length=16,
                        verbose_name="级别",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="标题")),
                ("detail", models.TextField(verbose_name="详情")),
                (
                    "admin_url",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="后台链接"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "处理中"), ("resolved", "已恢复")],
                        default="open",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("first_seen_at", models.DateTimeField(verbose_name="首次发现时间")),
                ("last_seen_at", models.DateTimeField(verbose_name="最近发现时间")),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近发送时间"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="恢复时间"
                    ),
                ),
                (
                    "notify_count",
                    models.PositiveIntegerField(default=0, verbose_name="通知次数"),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="最近发送错误"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近发送报错时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目告警状态",
                "verbose_name_plural": "项目告警状态",
                "db_table": "alerts_projecttelegramalertstate",
                "ordering": ("-last_seen_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectTelegramAlertConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "telegram_chat_id",
                    models.CharField(max_length=64, verbose_name="Telegram Chat ID"),
                ),
                (
                    "telegram_thread_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Telegram Thread ID",
                    ),
                ),
                (
                    "notify_on_withdrawal_stalled",
                    models.BooleanField(default=True, verbose_name="提币卡单告警"),
                ),
                (
                    "notify_on_deposit_collection_stalled",
                    models.BooleanField(default=True, verbose_name="归集卡单告警"),
                ),
                (
                    "notify_on_webhook_stalled",
                    models.BooleanField(default=True, verbose_name="Webhook 堆积告警"),
                ),
                (
                    "notify_on_recovery",
                    models.BooleanField(default=True, verbose_name="恢复通知"),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近验证时间"
                    ),
                ),
                (
                    "last_test_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近测试发送时间"
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, default="", verbose_name="最近错误"),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近报错时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目 Telegram 告警配置",
                "verbose_name_plural": "项目 Telegram 告警配置",
            },
        ),
    ]
