# Generated by Django 5.2.12 on 2026-04-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0002_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttelegramalertconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_project_telegram_alert_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="projecttelegramalertconfig",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_alert_config",
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.AddField(
            model_name="projecttelegramalertconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_project_telegram_alert_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectalertstate",
            constraint=models.UniqueConstraint(
                fields=("project", "event_type", "object_type", "object_pk"),
                name="uniq_project_alert_state_object",
            ),
        ),
    ]
