ERC20_TRANSFER_GAS = 100000
BASE_TRANSFER_GAS = 50000

HTTP_OK = 200

NOTIFICATION_MAX_FAILURES = 32

MIN_INVOICE_DURATION = 5
MAX_INVOICE_DURATION = 30


CALCULATE_BLOCK_TIME_COUNT = 32

LENGTH_OF_EVM_HASH = 66


APPID_HEADER = "XC-Appid"
NONCE_HEADER = "XC-Nonce"
SIGNATURE_HEADER = "XC-Signature"
TIMESTAMP_HEADER = "XC-Timestamp"


UPPER_ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
