# Generated by Django 5.2.12 on 2026-04-09 14:13

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePaySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本")),
                (
                    "pay_amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="支付加密货币数量"
                    ),
                ),
                (
                    "pay_address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="支付地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "生效中"),
                            ("matched", "已命中"),
                            ("discarded", "已丢弃"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "discard_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("overflow", "超上限淘汰"),
                            ("expired", "账单过期"),
                            ("settled", "已被其他付款占用"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="丢弃原因",
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="命中时间"
                    ),
                ),
                (
                    "discarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="丢弃时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "账单支付槽位",
                "verbose_name_plural": "账单支付槽位",
                "ordering": ("-version", "-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sys_no",
                    common.fields.SysNoField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=32,
                        prefix="INV",
                        unique=True,
                        verbose_name="系统单号",
                    ),
                ),
                ("out_no", models.CharField(db_index=True, verbose_name="商户单号")),
                ("title", models.CharField(verbose_name="标题")),
                ("currency", models.CharField(verbose_name="计价货币")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="金额"
                    ),
                ),
                (
                    "methods",
                    models.JSONField(default=dict, verbose_name="支持的支付方式"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="如果设置邮箱，在Invoice创建后会自动发送支付链接到此邮箱地址。",
                        max_length=254,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="支付加密货币数量可能在原始数量上差额浮动",
                        max_digits=32,
                        null=True,
                        verbose_name="支付加密货币数量",
                    ),
                ),
                (
                    "pay_address",
                    common.fields.AddressField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="支付地址",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="支付开始时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="支付截止时间")),
                (
                    "redirect_url",
                    models.URLField(blank=True, verbose_name="支付成功后重定向地址"),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="价值(USD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "待支付"),
                            ("confirming", "确认中"),
                            ("completed", "已完成"),
                            ("expired", "已超时"),
                        ],
                        default="waiting",
                        verbose_name="状态",
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("dash", "后台"),
                            ("shopify", "Shopify"),
                        ],
                        default="api",
                        max_length=16,
                        verbose_name="创建方式",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.crypto",
                        verbose_name="加密货币",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "ordering": ("-created_at",),
            },
        ),
    ]
