# Generated by Django 5.2.12 on 2026-04-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("currencies", "0001_initial"),
        ("invoices", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transfer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chains.onchaintransfer",
                verbose_name="链上转账",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayslot",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
                verbose_name="链",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayslot",
            name="crypto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="currencies.crypto",
                verbose_name="加密货币",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayslot",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pay_slots",
                to="invoices.invoice",
                verbose_name="账单",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayslot",
            name="project",
            field=models.ForeignKey(
                db_constraint=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="项目",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("project", "out_no"), name="uniq_invoice_project_out_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicepayslot",
            constraint=models.UniqueConstraint(
                fields=("invoice", "version"), name="uniq_invoice_pay_slot_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicepayslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("project", "crypto", "chain", "pay_address", "pay_amount"),
                name="uniq_invoice_pay_slot_active",
            ),
        ),
    ]
