# Generated by Django 5.2.12 on 2026-05-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("projects", "0003_refine_gather_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="protocol",
            field=models.CharField(
                choices=[("native", "Xcash 原生"), ("epay_v1", "EPay V1")],
                db_index=True,
                default="native",
                max_length=16,
                verbose_name="接入协议",
            ),
        ),
        migrations.CreateModel(
            name="EpayMerchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="EPay 商户 ID"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="留空时使用项目 HMAC 密钥。",
                        max_length=128,
                        verbose_name="EPay 密钥",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="CNY", max_length=8, verbose_name="默认计价货币"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epay_merchant",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPay 商户",
                "verbose_name_plural": "EPay 商户",
            },
        ),
        migrations.CreateModel(
            name="EpayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=32, verbose_name="EPay 商户 ID")),
                (
                    "trade_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="EPay 平台订单号"
                    ),
                ),
                (
                    "out_trade_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="商户订单号"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="支付类型"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="商品名称")),
                (
                    "money",
                    models.DecimalField(
                        decimal_places=2, max_digits=32, verbose_name="订单金额"
                    ),
                ),
                ("notify_url", models.URLField(verbose_name="异步通知地址")),
                (
                    "return_url",
                    models.URLField(
                        blank=True, default="", verbose_name="同步跳转地址"
                    ),
                ),
                (
                    "param",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="业务扩展参数",
                    ),
                ),
                (
                    "sign_type",
                    models.CharField(
                        default="MD5", max_length=16, verbose_name="签名类型"
                    ),
                ),
                (
                    "raw_request",
                    models.JSONField(default=dict, verbose_name="原始请求"),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="通知成功时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epay_order",
                        to="invoices.invoice",
                        verbose_name="账单",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="invoices.epaymerchant",
                        verbose_name="EPay 商户",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPay 订单",
                "verbose_name_plural": "EPay 订单",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("merchant", "out_trade_no"),
                        name="uniq_epay_order_merchant_out_trade_no",
                    ),
                    models.UniqueConstraint(
                        fields=("merchant", "trade_no"),
                        name="uniq_epay_order_merchant_trade_no",
                    ),
                ],
            },
        ),
    ]
