# Generated by Django 5.2.12 on 2026-05-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_epay_v1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="generated_by",
        ),
    ]
