# Generated by Django 5.2.12 on 2026-05-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_remove_invoice_generated_by"),
        ("webhooks", "0002_webhookevent_delivery_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epayorder",
            name="notified_at",
        ),
        migrations.AddField(
            model_name="epayorder",
            name="notify_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="webhooks.webhookevent",
                verbose_name="通知事件",
            ),
        ),
    ]
