# Generated by Django 5.2.12 on 2026-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_remove_epayorder_notified_at_epayorder_notify_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epaymerchant",
            name="default_currency",
            field=models.CharField(
                choices=[("CNY", "人民币"), ("USD", "美元")],
                default="CNY",
                max_length=8,
                verbose_name="默认计价货币",
            ),
        ),
        migrations.AlterField(
            model_name="epaymerchant",
            name="secret_key",
            field=models.CharField(
                help_text="EPay 协议签名密钥。建议使用强随机字符串，不要与项目 HMAC 密钥重用。",
                max_length=128,
                verbose_name="EPay 密钥",
            ),
        ),
    ]
