# Generated by Django 5.2.12 on 2026-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_backfill_epay_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="notify_url",
            field=models.URLField(blank=True, default="", verbose_name="异步通知地址"),
        ),
    ]
