# Generated by Django 5.2.12 on 2026-05-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_invoice_notify_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="email",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="return_url",
            field=models.URLField(
                blank=True, default="", verbose_name="支付成功后同步跳转地址"
            ),
        ),
    ]
