# Generated by Django 5.2.12 on 2026-05-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_remove_invoice_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low"),
                    ("Moderate", "Moderate"),
                    ("High", "High"),
                    ("Severe", "Severe"),
                ],
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="风险等级",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="risk_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="风险分数",
            ),
        ),
    ]
