# Generated by Django 5.2.12 on 2026-04-13 12:48

import common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("currencies", "0001_initial"),
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chains.onchaintransfer",
                        verbose_name="链上转账",
                    ),
                ),
            ],
            options={
                "verbose_name": "金库注资",
                "verbose_name_plural": "金库注资",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sys_no",
                    common.fields.SysNoField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=8,
                        max_length=32,
                        prefix="WDR-",
                        unique=True,
                        verbose_name="系统单号",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=32, verbose_name="数量"
                    ),
                ),
                (
                    "worth",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=16,
                        verbose_name="价值(USD)",
                    ),
                ),
                ("out_no", models.CharField(max_length=128, verbose_name="商户单号")),
                (
                    "to",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="收币地址"
                    ),
                ),
                (
                    "hash",
                    common.fields.HashField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=False,
                        verbose_name="哈希",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reviewing", "审核中"),
                            ("pending", "待执行"),
                            ("confirming", "确认中"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                            ("failed", "已失败"),
                        ],
                        default="pending",
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "broadcast_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.broadcasttask",
                        verbose_name="链上任务",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.crypto",
                        verbose_name="代币",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customer",
                        verbose_name="用户",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chains.onchaintransfer",
                        verbose_name="链上转账",
                    ),
                ),
            ],
            options={
                "verbose_name": "提币",
                "verbose_name_plural": "提币",
            },
        ),
        migrations.CreateModel(
            name="WithdrawalReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "已批准"), ("rejected", "已拒绝")],
                        verbose_name="操作",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("reviewing", "审核中"),
                            ("pending", "待执行"),
                            ("confirming", "确认中"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                            ("failed", "已失败"),
                        ],
                        verbose_name="原状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("reviewing", "审核中"),
                            ("pending", "待执行"),
                            ("confirming", "确认中"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                            ("failed", "已失败"),
                        ],
                        verbose_name="目标状态",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="快照"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_review_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "withdrawal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="withdrawals.withdrawal",
                        verbose_name="提币",
                    ),
                ),
            ],
            options={
                "verbose_name": "提币审核日志",
                "verbose_name_plural": "提币审核日志",
            },
        ),
        migrations.AddConstraint(
            model_name="withdrawal",
            constraint=models.UniqueConstraint(
                fields=("project", "out_no"), name="uniq_withdrawal_project_out_no"
            ),
        ),
    ]
